version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sanatana-dharma-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./server/models:/app/models:ro  # Read-only model files
      - ./server/logs:/app/logs         # Logs directory
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sanatana-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          memory: 2G

  # Frontend Service (Nginx)
  frontend:
    image: nginx:alpine
    container_name: sanatana-dharma-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - backend
    networks:
      - sanatana-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sanatana-network:
    driver: bridge

volumes:
  model_data:
  logs_data:

